//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_DemoExam_11_5_2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductOfOrders = new HashSet<ProductOfOrder>();
        }
    
        public string Article { get; set; }
        public string Name { get; set; }
        public string Measure { get; set; }
        public decimal Cost { get; set; }
        public int MaxDiscount { get; set; }
        public string Producer { get; set; }
        public string Provider { get; set; }
        public string CurrentDiscount { get; set; }
        public int Count { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int CategoryId { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOfOrder> ProductOfOrders { get; set; }
    }
}
